language: bash
sudo: required
addons:
  apt:
    packages: shellcheck
os:
 - linux
 - osx
script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then shellcheck init.sh; fi
 - ./init.sh -y
notifications:
  email: false
